name: Deployment 🚀

on:
  workflow_call:
    inputs:
      major_version:
        required: true
        type: string
      minor_version:
        required: true
        type: string
      build_version:
        required: true
        type: string
    secrets:
      DEPLOY_SSH_PRIVATE_KEY:
        required: true
      DEPLOY_SSH_USER:
        required: true
      DEPLOY_SERVER:
        required: true
      DEPLOY_SSH_PORT:
        required: true
      DEPLOY_DIR:
        required: true
      DATA_DIR:
        required: true
      DOCKER_HUB_USER:
        required: true
      DOCKER_IMAGE_NAME:
        required: true

jobs:
  deploy:
    name: Deployment 🚀
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Init Runner ⚙️
        uses: UnterrainerInformatik/init-runner-action@v1

      - name: Installing SSH key 🔑
        uses: UnterrainerInformatik/setup-ssh-action@v1
        with:
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}

      - name: Create deploy directory 🚧
        uses: UnterrainerInformatik/ssh-mkdir-action@v1
        with:
          dir: ${{ secrets.DEPLOY_DIR }}
          user: ${{ secrets.DEPLOY_SSH_USER }}
          host: ${{ secrets.DEPLOY_SERVER }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}

      - name: Create data directory 🚧
        uses: UnterrainerInformatik/ssh-mkdir-action@v1
        with:
          dir: ${{ secrets.DATA_DIR }}
          user: ${{ secrets.DEPLOY_SSH_USER }}
          host: ${{ secrets.DEPLOY_SERVER }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}

      - name: Touch version.js file for deployment
        run: touch ./deploy/version.js

      - name: Fill version.js file for deployment
        env:
          MAJOR_VERSION: ${{ inputs.major_version }}
          MINOR_VERSION: ${{ inputs.minor_version }}
          BUILD_VERSION: ${{ inputs.build_version }}
        run: |
          cat <<EOF > ./deploy/version.js
          window.version = (() => {
            return {
              VERSION: '${MAJOR_VERSION}.${MINOR_VERSION}.${BUILD_VERSION}',
              MAJOR_VERSION: '${MAJOR_VERSION}',
              MINOR_VERSION: '${MINOR_VERSION}',
              BUILD_VERSION: '${BUILD_VERSION}'
            }
          })()
          EOF

      - name: Touch .env file for deployment
        run: touch ./deploy/.env

      - name: Fill .env file for deployment
        run: |
          echo VERSION=${{ inputs.major_version }}.${{ inputs.minor_version }}.${{ inputs.build_version }} >> ./deploy/.env
          echo MAJOR_VERSION=${{ inputs.major_version }} >> ./deploy/.env
          echo MINOR_VERSION=${{ inputs.minor_version }} >> ./deploy/.env
          echo BUILD_VERSION=${{ inputs.build_version }} >> ./deploy/.env
          echo DOCKER_HUB_USER=${{ secrets.DOCKER_HUB_USER }} >> ./deploy/.env
          echo DOCKER_IMAGE_NAME=${{ secrets.DOCKER_IMAGE_NAME }} >> ./deploy/.env

      - name: Deploy using SSH 🚛
        uses: UnterrainerInformatik/ssh-deploy-action@v1
        with:
          source: ./deploy/
          target: ${{ secrets.DEPLOY_DIR }}
          chmod-mask: 777
          chmod-selector: ./deploy/*.sh
          user: ${{ secrets.DEPLOY_SSH_USER }}
          host: ${{ secrets.DEPLOY_SERVER }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}

      - name: Run using SSH 🏃
        uses: UnterrainerInformatik/ssh-run-action@v1
        with:
          dir: ${{ secrets.DEPLOY_DIR }}
          file: up.sh
          user: ${{ secrets.DEPLOY_SSH_USER }}
          host: ${{ secrets.DEPLOY_SERVER }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
