name: Deployment 🚀

on:
  workflow_call:
    inputs:
      major_version:
        required: true
        type: string
      minor_version:
        required: true
        type: string
      build_version:
        required: true
        type: string
      ovpn_enabled:
        required: false
        type: boolean
        default: false
    secrets:
      DEPLOY_SSH_PRIVATE_KEY:
        required: true
      DEPLOY_SSH_USER:
        required: true
      DEPLOY_SERVER:
        required: true
      DEPLOY_SSH_PORT:
        required: true
      DEPLOY_DIR:
        required: true
      DATA_DIR:
        required: true
      DOCKER_HUB_USER:
        required: true
      DOCKER_IMAGE_NAME:
        required: true
      VPN_OVPN_FILE:
        required: false
      VPN_USERNAME:
        required: false
      VPN_PASSWORD:
        required: false

jobs:
  deploy:
    name: Deployment 🚀
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Init Runner ⚙️
        uses: UnterrainerInformatik/init-runner-action@master

      - name: Install OpenVPN 🛜
        if: ${{ inputs.ovpn_enabled }}
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved

      - name: Write OVPN config
        if: ${{ inputs.ovpn_enabled }}
        run: |
          echo "${{ secrets.VPN_OVPN_FILE }}" >> client.ovpn

      - name: Connect to VPN 🔓
        if: ${{ inputs.ovpn_enabled }}
        uses: kota65535/github-openvpn-connect-action@v3
        with:
          config_file: client.ovpn
          username: ${{ secrets.VPN_USERNAME }}
          password: ${{ secrets.VPN_PASSWORD }}

      - name: Installing SSH key 🔑
        uses: UnterrainerInformatik/setup-ssh-action@master
        with:
          key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}

      - name: Create deploy directory 🚧
        uses: UnterrainerInformatik/ssh-mkdir-action@master
        with:
          dir: ${{ secrets.DEPLOY_DIR }}
          user: ${{ secrets.DEPLOY_SSH_USER }}
          host: ${{ secrets.DEPLOY_SERVER }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}

      - name: Create data directory 🚧
        uses: UnterrainerInformatik/ssh-mkdir-action@master
        with:
          dir: ${{ secrets.DATA_DIR }}
          user: ${{ secrets.DEPLOY_SSH_USER }}
          host: ${{ secrets.DEPLOY_SERVER }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}

      - name: Touch version.js file
        run: touch ./deploy/version.js

      - name: Fill version.js file
        env:
          MAJOR_VERSION: ${{ inputs.major_version }}
          MINOR_VERSION: ${{ inputs.minor_version }}
          BUILD_VERSION: ${{ inputs.build_version }}
        run: |
          cat <<EOF > ./deploy/version.js
          window.version = (() => {
            return {
              VERSION: '${MAJOR_VERSION}.${MINOR_VERSION}.${BUILD_VERSION}',
              MAJOR_VERSION: '${MAJOR_VERSION}',
              MINOR_VERSION: '${MINOR_VERSION}',
              BUILD_VERSION: '${BUILD_VERSION}'
            }
          })()
          EOF

      - name: Touch .env file
        run: touch ./deploy/.env

      - name: Fill .env file
        run: |
          echo VERSION=${{ inputs.major_version }}.${{ inputs.minor_version }}.${{ inputs.build_version }} >> ./deploy/.env
          echo MAJOR_VERSION=${{ inputs.major_version }} >> ./deploy/.env
          echo MINOR_VERSION=${{ inputs.minor_version }} >> ./deploy/.env
          echo BUILD_VERSION=${{ inputs.build_version }} >> ./deploy/.env
          echo DOCKER_HUB_USER=${{ secrets.DOCKER_HUB_USER }} >> ./deploy/.env
          echo DOCKER_IMAGE_NAME=${{ secrets.DOCKER_IMAGE_NAME }} >> ./deploy/.env

      - name: Deploy using SSH 🚛
        uses: UnterrainerInformatik/ssh-deploy-action@master
        with:
          source: ./deploy/
          target: ${{ secrets.DEPLOY_DIR }}
          chmod-mask: 777
          chmod-selector: ./deploy/*.sh
          user: ${{ secrets.DEPLOY_SSH_USER }}
          host: ${{ secrets.DEPLOY_SERVER }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}

      - name: Run using SSH 🏃
        uses: UnterrainerInformatik/ssh-run-action@master
        with:
          dir: ${{ secrets.DEPLOY_DIR }}
          file: up.sh
          user: ${{ secrets.DEPLOY_SSH_USER }}
          host: ${{ secrets.DEPLOY_SERVER }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
